### ISSUE TITLE
Event processor configuration gives error when configuring it for JWT

### ISSUE THREAD

**Issue by ymatienzo** [stellar/java-stellar-anchor-sdk#1406]
### What version are you using?
2.8.0

### What did you do?

I ran the anchor platform with the event processor service using a docker compose file as follows:

```version: "3.8"
services:

  db:
    image: postgres:14
    container_name: 'anchor-db'
    ports:
      - "5432:5432"
    env_file:
      - ./dev.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  sep-server:
    image: stellar/anchor-platform:2.8.0
    command: --sep-server
    container_name: sep-server
    ports:
      - "8080:8080"
    env_file:
      - ./dev.env
    volumes:
      - ./config:/home
    depends_on:
      - db

  platform-server:
    image: stellar/anchor-platform:2.8.0
    command: --platform-server
    container_name: platform-server
    ports:
      - "8085:8085"
    env_file:
      - ./dev.env
    volumes:
      - ./config:/home
    depends_on:
      - db

  event-processor:
    image: stellar/anchor-platform:2.8.0
    command: --event-processor
    container_name: 'event-processor'
    env_file:
      - ./dev.env
    volumes:
    - ./config:/home
    depends_on:
      - db
      - kafka
  
  business-server:
    image: anchor-business-server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ANCHOR_PLATFORM_API_URL='http://platform-server:8085'
      - ANCHOR_PLATFORM_JWT_SECRET=<the secret here>

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_BROKER_ID: 1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
      - zookeeper
```

I then configured the .env variables as follows:

```############ ASSETS #############

ASSETS_TYPE=file
ASSETS_VALUE=/home/dev.assets.yaml

############ SEP_1 #############
SEP1_ENABLED=true
SEP1_TOML_TYPE=file
SEP1_TOML_VALUE=/home/dev.stellar.toml

############ SEP_6 #############
SEP6_ENABLED=true
SEP6_MORE_INFO_URL_BASE_URL=http://example.com
SEP6_DEPOSIT_INFO_GENERATOR_TYPE='none'

############ SEP_10 #############
SEP10_ENABLED=true
SEP10_HOME_DOMAIN=localhost:8080

############ SEP_12 #############
SEP12_ENABLED=true

############ SEP_38 #############

SEP38_ENABLED=true

############ DATA #############
DATA_TYPE=postgres
DATA_SERVER=db
DATA_DATABASE=platform
DATA_FLYWAY_ENABLED=true
POSTGRES_USER=<the user>
POSTGRES_PASSWORD=<the password>

########### CALLBACK_API #############
CALLBACK_API_BASE_URL=http://server:3000
CALLBACK_API_AUTH_TYPE=jwt

############ EVENT_PROCESSOR #############
EVENT_PROCESSOR_CALLBACK_API_REQUEST_ENABLED=true

############ EVENT_QUEUE #############
EVENTS_ENABLED=true
EVENTS_QUEUE_TYPE=kafka
EVENTS_QUEUE_KAFKA_BOOTSTRAP_SERVER='kafka:9092'
EVENTS_QUEUE_KAFKA_CLIENT_ID=ap-event-service


############ Platform API Authentication #############

PLATFORM_SERVER_AUTH_TYPE=jwt
PLATFORM_API_BASE_URL=http://platform-server:8085
PLATFORM_API_AUTH_TYPE=jwt


############ SECRETS #############

SECRET_DATA_USERNAME=<username>
SECRET_DATA_PASSWORD=<password>
SECRET_SEP6_MORE_INFO_URL_JWT_SECRET=<secret>
SECRET_SEP10_SIGNING_SEED='<private key>
SECRET_SEP10_JWT_SECRET=<secret>
SECRET_PLATFORM_API_AUTH_SECRET=<secret>
SECRET_CALLBACK_API_AUTH_SECRET=<secret>
```
### What happened?

I've got the following error in the event-processor logs:

```2024-06-29 00:04:11 22:04:11.806 ERROR - o.s.a.p.e.CallbackApiEventHandler - Failed to send event to callback API. Error code: {}
2024-06-29 00:04:11 org.stellar.anchor.api.exception.InvalidConfigException: Please provide the secret before encoding JWT for API Authentication
2024-06-29 00:04:11     at org.stellar.anchor.auth.JwtService.encode(JwtService.java:163)
2024-06-29 00:04:11     at org.stellar.anchor.auth.JwtService.encode(JwtService.java:154)
2024-06-29 00:04:11     at org.stellar.anchor.auth.AuthHelper.createJwt(AuthHelper.java:102)
2024-06-29 00:04:11     at org.stellar.anchor.auth.AuthHelper.createAuthHeader(AuthHelper.java:85)
2024-06-29 00:04:11     at org.stellar.anchor.auth.AuthHelper.createPlatformServerAuthHeader(AuthHelper.java:59)
2024-06-29 00:04:11     at org.stellar.anchor.apiclient.BaseApiClient.getRequestBuilder(BaseApiClient.java:58)
2024-06-29 00:04:11     at org.stellar.anchor.apiclient.CallbackApiClient.sendEvent(CallbackApiClient.java:55)
2024-06-29 00:04:11     at org.stellar.anchor.platform.event.CallbackApiEventHandler.handleEvent(CallbackApiEventHandler.java:27)
2024-06-29 00:04:11     at org.stellar.anchor.platform.event.CallbackApiEventProcessor.handleEventWithRetry(CallbackApiEventProcessor.java:33)
2024-06-29 00:04:11     at org.stellar.anchor.platform.event.EventProcessor.run(EventProcessor.java:66)
2024-06-29 00:04:11     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-06-29 00:04:11     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2024-06-29 00:04:11     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2024-06-29 00:04:11     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-06-29 00:04:11     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-06-29 00:04:11     at java.base/java.lang.Thread.run(Thread.java:840)
```

### What did you expect to see instead?

I would not expect this error. The idea is for the event processor to generate a JWT token signed with the SECRET_CALLBACK_API_AUTH_SECRET enviromental variable and to send it to the business server as a Authorization Bearer token in the header. 

This only happen when configuring the CALLBACK_API_AUTH_TYPE environmental variable as "jwt". If I instead configure it as  "api_key" the error does not happen and the event processor sends the callback request correctly.

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @ymatienzo

**Comment by Ifropc** [comment]
Hi @ymatienzo thanks for reporting this issue and sorry for the delayed response, as a lot of our team members are/were currently out vacationing 🍹 
This issue should be fixed in https://github.com/stellar/java-stellar-anchor-sdk/pull/1420 for which we will release 2.8.3
